export const CUISINES = [
  'North Indian',
  'South Indian',
  'Punjabi',
  'Gujarati',
  'Rajasthani',
  'Bengali',
  'Maharashtrian',
  'Kerala',
  'Hyderabadi',
  'Mughlai',
  'Kashmiri',
  'Goan',
  'Konkani',
  'Mangalorean',
  'Sindhi',
  'Bihari',
  'Awadhi',
  'Andhra',
  'Tamil',
  'Chettinad',
  'Karnataka',
  'Udupi',
  'Indo-Chinese',
  'Chinese',
  'Italian',
  'Continental',
  'Korean',
  'Mexican',
  'Street Food',
  'Fusion',
  'Pan-Indian',
] as const

export const BLOCKLIST_CHIP_ROTATIONS = [
  'rotate-[2deg]',
  '-rotate-[1.5deg]',
  'rotate-[3deg]',
  '-rotate-[2.5deg]',
  'rotate-[1deg]',
]
